config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    invitations: 'users/invitations'
  } do
    # match 'settings', to: 'users/registrations#settings'
  end
  match 'auth/failure', to: redirect('/'), via: [:get]
  match 'search', to: 'listings#search', as: 'search', via: [:get]

  match 'profile', to: 'users#profile', as: 'my_profile', via: [:get]

  resources :messages, only: [:index, :show, :create]
  resources :conversations, only: [:index, :show]
  resources :users do
    collection do
      get :settings
      put :upload_avatar
      delete :delete_avatar
    end
  end
  resources :pictures
  resources :listings

  namespace :api, defaults: { format: :json } do
    get '/users/current'
    post '/rate' => 'rater#create', :as => 'rate'
    resources :users do
      collection do
        put 'newsletter_notifcations'
        put 'messages_notifcations'
      end
      member do
        get 'products'
      end
    end
    resources :products, only: [:index, :show]
    resources :requests
    resources :cities, only: :index
    resources :assets do
      member do
        delete 'delete_new_asset'
      end
    end
    resources :tags, only: :index
    resources :messages, only: :create
    resources :conversations, only: [:index, :show]
  end

  authenticated do
    root :to => 'listings#search', as: :authenticated
  end

  root to: 'home_page#index'
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_filter :load_product, except: [:index, :new, :create, :search]
  before_filter :validate_owner, except: [:index, :show, :new, :create, :search]

  def index
  end

  def show
  end

  def search
  end

  def new
    @product = Product.new
    @my_unique_token = SecureRandom.hex(16)
  end

  def edit
    @my_unique_token = SecureRandom.hex(16)
  end

  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        @product.take_assets(params[:my_unique_token])
        format.html { redirect_to listing_path(@product), notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product}
      else
        @my_unique_token = SecureRandom.hex(16)
        format.html { render action: 'new', error: 'Error....' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        @product.take_assets(params[:my_unique_token])
        format.html { redirect_to listing_path(@product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        @my_unique_token = SecureRandom.hex(16)
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private

  def load_product
    @product = Product.find(params[:id])
  end

  def validate_owner
    unless @product.user == current_user
      flash[:error] = 'You are not authorized to access this page.'
      redirect_to listing_path(@product)
    end
  end

  def product_params
    params.require(:product).permit(:title, :category_id, :user_id,
                                    :tag_list, :price_per_day, :total_value,
                                    :details, :is_available, :available_at,
                                    :end_at, :address, :country, :postal_code, :locality,
                                    :latitude, :longitude, :administrative_area_level_2, :administrative_area_level_1,
                                    :location_type, assets_attributes:[:image])
  end
end

app/views/listings/_assets.html.erb
<div class="modal fade" id="uploadAssets" tabindex="-1" role="dialog" aria-labelledby="uploadAssetsLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="uploadAssetsLabel">Upload photos</h4>
      </div>
      <div class="modal-body">
        <%= form_tag '/pictures', method: :post, class: "dropzone form", id: "media-dropzone" do %>
          <div class="fallback">
            <%= file_field_tag "media", multiple: true%>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/listings/_form.haml
#listings-edit-add-vue
  %aside.prod-reg.left.col-xs-12.col-sm-6.col-md-6.col-lg-6
    = f.text_field :title, class: 'meet-location inp-bg', placeholder: "Title"
    = f.select :category_id, Category.all.map{|cat| [cat.name, cat.id]}, {include_blank: "Category"}, class: 'meet-location inp-bg'
    /= f.text_field :category, class: 'meet-location inp-bg', placeholder: "Category"
    .category-total
      %span.meet-location.inp-bg.left.col-xs-12.col-sm-6.col-md-6.col-lg-8= "Price (per day)"
      = f.text_field :price_per_day, class: 'meet-location left col-xs-12 col-sm-6 col-md-6 col-lg-4', placeholder: "$"
      %span.meet-location.inp-bg.left.col-xs-12.col-sm-6.col-md-6.col-lg-8= "Total Equipment Value"
      = f.text_field :total_value, class: 'meet-location left col-xs-12 col-sm-6 col-md-6 col-lg-4', placeholder: "$"

    = f.text_area :details, class: 'inp-bg', placeholder: "Details"
    = f.text_field :tag_list, class: 'meet-location inp-bg', placeholder: 'Tags (separated by commas)'
    .inp-bg
      .top-calendar
        .left= 'Availability'
        .right
          = f.check_box :is_available
          = 'Available Forever'
        .clear
      = f.hidden_field :available_at
      = f.hidden_field :end_at
      #rangeCalendar
      //.done.right== <a href="#">Done</a>
      .clear
  %aside.listing.right.col-xs-12.col-sm-6.col-md-6.col-lg-6
    .rit
      = link_to 'Add Pictures', '#', class: 'add-picture inp-bg', data: {toggle: 'modal', target: '#uploadAssets'}
      //= render partial: 'listings/upload_assets', locals: {f: f}
      .slide-images
        = hidden_field_tag :my_unique_token, @my_unique_token

        //= image_tag('slide-image.jpg')
        #media-contents
          %ul.lenyt-slider
            %li{"v-repeat" => "images", "v-class" => "current:current, previous:previous, next:next"}
              %img{"v-attr" => "src:url"}
          %span.remove-image{"v-on" => "click: removeImage"} Remove
          .slide-controls{"v-class" => "hidden:imagesLength <= 1"}
            = link_to image_tag('arrow-left.png'), '#', class: 'carousel_link', "v-on" => "click:prev"
            %span
              %span.current_slide> {{current+1}}
              \/
              %span.slides_count {{imagesLength}}
            = link_to image_tag('arrow-right.png'), '#', class: 'carousel_link', "v-on" => "click:next"
      = f.text_field :address, class: 'meet-location inp-bg', placeholder: 'Meet Location', autocomplete: :off
      .map-list#map

      = f.hidden_field :country
      = f.hidden_field :postal_code
      = f.hidden_field :locality
      = f.hidden_field :latitude
      = f.hidden_field :longitude
      = f.hidden_field :administrative_area_level_2
      = f.hidden_field :administrative_area_level_1
      = f.hidden_field :location_type

app/views/listings/_one_listing.haml
.col-xs-12.col-sm-6
  .shadow-box.list
    .new-listing.col-xs-10
      .img-content= image_tag('small-img.jpg')
      .list-detail
        .product-title= "Leica M9 with 50mm f2.0"
        = link_to '$50', '#', class: 'request'
    .col-xs-2
      = link_to "", "#", class: 'edit'
      = link_to "", "#", class: 'delete'
    .clear

app/views/listings/_products.haml
- current_user.products.each do |product|
  .col-xs-12.col-sm-6
    .shadow-box.list
      .new-listing.col-xs-10
        .img-content
          - img = product.assets.first
          -  if img.present?
            = image_tag(img.image.url(:small))
          - else
            = image_tag('small-img.jpg')

        .list-detail
          .product-title= product.title
          = link_to  "$#{product.price_per_day}", listing_path(product), class: 'request'
      .col-xs-2
        = link_to "", edit_listing_path(product), class: 'edit'
        = link_to "", listing_path(product), {confirm: "Are you sure?", method: :delete, class: 'delete'}
      .clear

app/views/listings/_search_one_list.haml
.product-list
  .product-description.col-xs-12.col-sm-12.col-md-12.col-lg-12
    .img-content
      = image_tag('small-img.jpg')
    .product-title Leica M9 with 50mm f2.0
    .user-line
      .img-content
        = image_tag('emma.png')
      .stars
        %span.star-active.star
        %span.star-active.star
        %span.star-active.star
        %span.star-inactive.star
        %span (17)
      .distance 15km
  .product-price.col-xs-1.col-sm-1.col-md-1.col-lg-1 $50

app/views/listings/_slider.html.erb
<div id="carousel" class="carousel slide" data-ride="carousel">
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @product.assets.each_with_index do |a, index| %>
    <div class="carousel_slider item <%= 'active' if index == 0 %>">
      <%= image_tag(a.image.url(:large)) %>
    </div>
    <% end %>
  </div>
</div>

<div class="slide-controls">
  <%= link_to image_tag('arrow-left.png'), '#', class: 'carousel_link', data: {move: 'prev'} %>
  <span><span class='current_slide'>0</span>/<span class='slides_count'>0</span></span>
  <%= link_to image_tag('arrow-right.png'), '#', class: 'carousel_link', data: {move: 'next'} %>
</div>


<script type="text/javascript">
$('.carousel').carousel({
  interval: false
})

slides_count = $('.carousel_slider').length
$('.slides_count').html(slides_count);

current_slide = ((slides_count > 0) ? 1 : 0);

$('.current_slide').html(current_slide);

$('.carousel_link').click(function(event) {
  event.preventDefault();
  direction = $(this).data('move');
  $('.carousel').carousel(direction);
  setTimeout(function(){
    $('.current_slide').html($('.carousel .active').index('.carousel .item')+1);
  }, 600);
});
</script>

app/views/listings/edit.haml
= content_for :gmap_api do
  = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&language=el'

= render 'assets'
%section.content
  = form_for @product, url: listing_path(@product), html: {method: :put, multipart: true } do |f|
    = render 'shared/errors', resource: @product
    = render partial: 'form', locals: {f: f}
    = f.submit "Update product", class: 'list-it col-xs-12 col-sm-12 col-md-12 col-lg-12 btn', id: 'new-listing'

app/views/listings/new.haml
= render 'assets'
%section.content
  = form_for @product, url: listings_path, html: {method: :post, multipart: true } do |f|
    = render 'shared/errors', resource: @product
    = render partial: 'form', locals: {f: f}
    = f.submit "List It", class: 'list-it col-xs-12 col-sm-12 col-md-12 col-lg-12 btn', id: 'new-listing'

app/views/listings/search.haml
#lenyt-search
  %section.content
    %section.search-bar
      .search-input.col-xs-12.col-sm-6.col-md-6.col-lg-2
        %input.drop{"data-toggle" => "dropdown", :placeholder => "category", :type => "text", "v-model" => "category.name"}/
        %ul.dropdown-menu.dropdown-menu-cat{"aria-labelledby" => "dLabel", :role => "menu"}
          %li
            %a{href: "#", "v-on" => "click: selectCategory(0, '')"} All
          - Category.order(name: :asc).each do |cat|
            %li
              %a{href: "#", data: {id: cat.id}, "v-on" => "click: selectCategory(#{cat.id}, '#{cat.name}')"}
                =cat.name
      .search-input.col-xs-12.col-sm-6.col-md-6.col-lg-4
        %input#tag-input{:type => "text", "v-model" => "tags.searchTerm", "v-on" => "focus:tags.visible = true, blur: hideTags, keyup: findTags", "v-attr" => "placeholder: tags.placeholder"}
        %ul.dropdown-menu.dropdown-menu-cat{"v-class" => "display-block: tags.visible === true"}
          %li{"v-on" => "click: deSelectTag"}
            %a{:href => "#"}
              All
          %li{"v-repeat" => "tags.list", "v-class" => "current-tag: $index === tags.current", "v-on" => "click: selectTag($index)", "v-class" => "hide: $index > 3"}
            %a{:href => "#"}
              {{name}}
              %span{"v-class" => "hide: !taggings_count"} ({{taggings_count}} listings)
      .search-input.col-xs-12.col-sm-6.col-md-6.col-lg-3
        %input{:placeholder => "where", :type => "text", "v-model" => "city.search", "v-on" => "focus: city.visible = true, blur: hideCity, keyup: findCity"}
        %ul.dropdown-menu.dropdown-menu-cat{"v-class" => "display-block: city.visible === true"}
          %li{"v-repeat" => "city.list", "v-on" => "click: setCity(name)"}
            %a{:href => "#"}
              {{name}}
              %span{"v-class" => "hide: !state"}, {{state}}
      .input-daterange
        .search-input.col-xs-12.col-sm-3.col-md-3.col-lg-3.no-padding
          .col-md-6
            %input{:name => "start", :type => "text", placeholder: 'from'}/
          .col-md-6
            %input{:name => "end", :type => "text", placeholder: 'to'}/
      .clear
    %aside.map-points.slide.left.col-xs-12.col-sm-6.col-md-6.col-lg-6
      #search_map
      //= image_tag('map-big.jpg')

      .map-pointi
        %a.map-point{href:"http://lenyt-dev.herokuapp.com/listings/ID"}
          %img{alt:"", src: "IMAGE_URL"}
          .title-popover TITLE
          %span.price-popover PRICE
          .clear
    %aside.user-request.right.col-xs-12.col-sm-6.col-md-6.col-lg-6
      .rit
        .range-sort
          .row
            .col-md-12
              .col-md-6
                %span
                  $
                  %div.start_range 0
                %input#range.span2{"data-slider-max" => "1000", "data-slider-min" => "0", "data-slider-step" => "1", "data-slider-value" => "[0,1000]", :type => "text", :value => "0,1000"}/
                %span
                  $
                  %div.end_range
                    1000
              .search-input.col-md-6
                %input.sort{"data-toggle" => "dropdown", :placeholder => "sort by", :type => "text"}/
                %ul.dropdown-menu.dropdown-menu-cat{"aria-labelledby" => "dLabel", :role => "menu"}
                  %li
                    %a{:href => "#"} price (low to high)
                  %li
                    %a{:href => "#"} price (high to low)
                  %li
                    %a{:href => "#"} proximity
        #product-listing{"v-on" => "scroll:scroll"}
          %template{"v-repeat" => "product: products"}

            %a{href: "listings/{{product.id}}"}
              .product-list{"v-on" => "hover: toggleActive", "v-class" => "transparent: active", data: {index: "{{$index}}"}}
                .product-description.col-xs-12.col-sm-12.col-md-12.col-lg-12
                  .img-content.product-avatar{"v-style" => "background-image: 'url(' + product.image + ')'"}
                  .product-title {{product.title}}
                  .user-line
                    .img-content
                      = image_tag('#', class: 'img-circle search-user-avatar', "v-attr" => "src:product.user.avatar")
                    .stars
                      %span.stars-active{"v-style" => "width:(product.user.rating.avg*20)+'px'"}
                    %span.rating_count ({{product.user.rating.count}})
                    .distance {{product.distance}}km
                .product-price.col-xs-1.col-sm-1.col-md-1.col-lg-1 ${{product.price_per_day}}

app/views/listings/show.haml
#lenyt-vue-listings-show
  .noticesWrapper.col-md-12.col-xs-12.col-sm-12{style:'float:none', "v-class" => "hide: alertMessage === ''"}
    .alert.alert-success
      %a.close{"v-on" => "click:closeAlert"}
        %i.fa.fa-times
      %span {{alertMessage}}
  %section.content
    .col-md-12
      .actions
        .price {{product.price_per_day | currency}}
        .pick-date
          %input#dpd1{:placeholder => "From", :type => "text"}
          %input#dpd2{:placeholder => "To", :type => "text"}
        .total
          %ul
            %li
              ='{{days}}'
              %span.small='day(s)'
            %li
              %span{"v-class" => "hide: insurance === 1"} {{product.total_value | currency}}
              %span{"v-class" => "hide: insurance === 2"} {{dw + (product.total_value / 4) | currency}}
              = raw(" ")
              %span.small total
    %aside.slide.left.col-xs-12.col-sm-6.col-md-6.col-lg-6
      .slide-images
        #media-contents
          %ul.lenyt-slider
            %li{"v-repeat" => "product.images", "v-class" => "current:current, previous:previous, next:next"}
              %img{class: 'img-responsive', "v-attr" => "src:url"}
          .slide-controls{"v-class" => "hidden:imagesLength <= 1"}
            = link_to image_tag('arrow-left.png'), '#', class: 'carousel_link', "v-on" => "click:prev"
            %span
              %span.current_slide> {{current+1}}
              \/
              %span.slides_count {{imagesLength}}
            = link_to image_tag('arrow-right.png'), '#', class: 'carousel_link', "v-on" => "click:next"
      .product-title {{product.title}}
    %aside.user-request.right.col-xs-12.col-sm-6.col-md-6.col-lg-6
      .rit
        .gray-box
          .insurance
            .col-xs-12.col-sm-6.col-md-6.col-lg-6
              %h3.bold-text Choose Insurance:
              %p.value-text= "Listing Value: {{product.total_value | currency}}"
            .waver.col-xs-12.col-sm-6.col-md-3.col-lg-3
              %h3 Damage Waver
              .text-box{"v-on" => "click: insuranceDW", "v-class" => "'text-box-active': insurance === 1"}
                %span.price-num {{dw | currency}}
                %span.price-description {{product.total_value / 4 | currency}} Refundable Deposit
            .deposit.col-xs-12.col-sm-6.col-md-3.col-lg-3
              %h3 Full Deposit
              .text-box{"v-on" => "click: insuranceFD", "v-class" => "'text-box-active': insurance === 2", class: 'full-deposit'}
                %span.price-num {{product.total_value | currency}}
                %span.price-description Refundable Deposit
            .clear
            %p.description Damage Waver: Covers this rental for its full duration. Requires a $450 hold on your credit card as a refundable deductible deposit.
        .user-req
          .user-stars.col-xs-6.col-sm-6.col-md-6.col-lg-4{"v-class" => "large: product.user.name === username"}
            %img.img-circle.img-url.user-avatar{alt:'', src: '', 'v-attr' => 'src:product.user.avatar'}
            -#= user_avatar(@owner)
            %span.user-name {{product.user.name}}
            .stars.ml60
              %span.stars-active{"v-style" => "width:(rating*20)+'px'"}
              .over{"v-on" => "mousemove:star, mouseout:resetStar, click:vote"}
          %a.request.col-xs-6.col-sm-6.col-md-6.col-lg-8{:href => "#", "v-on" => "click: request", "v-class" => "hide: product.user.name === username"} Request
          .clear
          .message
            Your credit card will not be charged until the user accepts your request. You can always view and cancel your requests from the
            %a{:href => "#"} Message
            board.
  %section.content.table-type
    %aside.product-details.left.col-xs-12.col-sm-6.col-md-6.col-lg-6
      .prov
        %p {{product.details}}
    %aside.map-side.right.col-xs-12.col-sm-6.col-md-6.col-lg-6
      .rit
        .meet-location
          %h3.left Suggested Meetup
          %h3.right=  @product.address
        #map-canvas.map{data: {lng: @product.longitude, lat: @product.latitude, address: @product.address}}