config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    invitations: 'users/invitations'
  } do
    # match 'settings', to: 'users/registrations#settings'
  end
  match 'auth/failure', to: redirect('/'), via: [:get]
  match 'search', to: 'listings#search', as: 'search', via: [:get]

  match 'profile', to: 'users#profile', as: 'my_profile', via: [:get]

  resources :messages, only: [:index, :show, :create]
  resources :conversations, only: [:index, :show]
  resources :users do
    collection do
      get :settings
      put :upload_avatar
      delete :delete_avatar
    end
  end
  resources :pictures
  resources :listings

  namespace :api, defaults: { format: :json } do
    get '/users/current'
    post '/rate' => 'rater#create', :as => 'rate'
    resources :users do
      collection do
        put 'newsletter_notifcations'
        put 'messages_notifcations'
      end
      member do
        get 'products'
      end
    end
    resources :products, only: [:index, :show]
    resources :requests
    resources :cities, only: :index
    resources :assets do
      member do
        delete 'delete_new_asset'
      end
    end
    resources :tags, only: :index
    resources :messages, only: :create
    resources :conversations, only: [:index, :show]
  end

  authenticated do
    root :to => 'listings#search', as: :authenticated
  end

  root to: 'home_page#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  username               :string
#  address                :string
#  city                   :string
#  state                  :string
#  country                :string
#  postal_code            :string
#  phone_number           :string
#  email                  :string           default(""), not null
#  password_salt          :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  provider               :string
#  uid                    :string
#  created_at             :datetime
#  updated_at             :datetime
#  image_url              :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  messages_notifcations             :boolean          default(TRUE)
#  newsletter_notifcations               :boolean          default(TRUE)
#

class User < ActiveRecord::Base
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable,
        :validatable,
        :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  ratyrate_rater
  ratyrate_rateable 'trust'

  validates :email, :username, presence: true
  validates :username, uniqueness: true
  acts_as_messageable

  has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /^image\/(png|gif|jpeg|jpg)/

  has_many :products
  has_many :requests, foreign_key: :renter_id
  has_many :sent_requests, class_name: 'Request', foreign_key: :rentee_id

  def self.from_omniauth(auth)
    username = User.parse_username(auth.info.name, auth.provider)
    user_hash = {
      first_name: auth.info.first_name,
      last_name: auth.info.last_name,
      username: username,
      image_url: auth.info.image,
      address: auth.info.address,
      email: auth.info.email,
      provider: auth.provider,
      uid: auth.uid,
      password: Devise.friendly_token[0, 20]
    }
    user = find_or_initialize_by(provider: auth.provider, uid: auth.uid)
    user.update_attributes(user_hash)
    user
  end

  def self.parse_username(string, provider)
    # (provider == 'google_oauth2') ? string[/\(.*?\)/].gsub('(', '').gsub(')', '') : auth.info.name
    string
  end

  def profile_picture
    return avatar.url(:thumb) if avatar.present?
    return image_url unless image_url.blank?
    ActionController::Base.helpers.asset_path 'default_avatar.png'
  end

  def full_name
    username.present? ? username : email
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    before_action :authenticate_user!
    respond_to :json

    def current
      render json: current_user, root: nil
    end

    def update
      @user = current_user

      respond_to do |format|
        if @user.update_attributes!(user_params)
          format.json { head :no_content }
        else
          format.json do
            render json: @user.errors, status: :unprocessable_entity
          end
        end
      end
    end

    def newsletter_notifcations
      user = current_user
      user.update_attributes!(newsletter_notifcations: params[:newsletter])
      render json: {}
    end

    def messages_notifcations
      user = current_user
      user.update_attributes!(messages_notifcations: params[:message])
      render json: {}
    end

    def products
      render json: current_user.products,
        each_serializer: UserProductsSerializer,
        root: 'products'
    end

    private

    def user_params
      params.require(:user).permit(
        :messages_notifcations, :newsletter_notifcations
      )
    end
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  respond_to :json
  layout false, only: :create

  prepend_before_filter :authenticate_inviter!, :only => [:new, :create]
  prepend_before_filter :has_invitations_left?, :only => [:create]
  prepend_before_filter :require_no_authentication, :only => [:edit, :update, :destroy]
  prepend_before_filter :resource_from_invitation_token, :only => [:edit, :destroy]
  helper_method :after_sign_in_path_for

  # GET /resource/invitation/new
  def new
    self.resource = resource_class.new
    render :new
  end

  # POST /resource/invitation
  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
      # if is_flashing_format? && self.resource.invitation_sent_at
      #   set_flash_message :notice, :send_instructions, :email => self.resource.email
      # end
      # respond_with resource, :location => after_invite_path_for(current_inviter)
      render json: {success: 'Invitation successfully sent'}
    else
      # respond_with_navigational(resource) { render :new }
      render json: {errors: resource.errors}
    end
  end

  # GET /resource/invitation/accept?invitation_token=abcdef
  def edit
    resource.invitation_token = params[:invitation_token]
    render :edit
  end

  # PUT /resource/invitation
  def update
    raw_invitation_token = update_resource_params[:invitation_token]
    self.resource = accept_resource
    invitation_accepted = resource.errors.empty?

    yield resource if block_given?

    if invitation_accepted
      if Devise.allow_insecure_sign_in_after_accept
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message :notice, flash_message if is_flashing_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_accept_path_for(resource)
      else
        set_flash_message :notice, :updated_not_active if is_flashing_format?
        respond_with resource, :location => new_session_path(resource_name)
      end
    else
      resource.invitation_token = raw_invitation_token
      respond_with_navigational(resource){ render :edit }
    end
  end

  # GET /resource/invitation/remove?invitation_token=abcdef
  def destroy
    resource.destroy
    set_flash_message :notice, :invitation_removed if is_flashing_format?
    redirect_to after_sign_out_path_for(resource_name)
  end

  protected

  def invite_resource(&block)
    resource_class.invite!(invite_params, current_inviter, &block)
  end

  def accept_resource
    resource_class.accept_invitation!(update_resource_params)
  end

  def current_inviter
    authenticate_inviter!
  end

  def has_invitations_left?
    unless current_inviter.nil? || current_inviter.has_invitations_left?
      self.resource = resource_class.new
      set_flash_message :alert, :no_invitations_remaining if is_flashing_format?
      respond_with_navigational(resource) { render :new }
    end
  end

  def resource_from_invitation_token
    unless params[:invitation_token] && self.resource = resource_class.find_by_invitation_token(params[:invitation_token], true)
      set_flash_message(:alert, :invitation_token_invalid) if is_flashing_format?
      redirect_to after_sign_out_path_for(resource_name)
    end
  end

  def invite_params
    devise_parameter_sanitizer.sanitize(:invite)
  end

  def update_resource_params
    devise_parameter_sanitizer.sanitize(:accept_invitation)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :js
  layout false, only: :create
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :js
  layout false, only: :create
  skip_before_filter :publish_session

  def new
    super
  end

  def create
    self.resource = warden.authenticate(auth_options)
    return unless resource && resource.active_for_authentication?
    sign_in(resource_name, resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    current_user
  end

  def settings
  end

  def update
    @user = current_user

    #raise current_user.inspect
    respond_to do |format|
      if @user.update_attributes!(user_params)
        format.html { redirect_to settings_users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        @user = current_user
        format.html { render action: 'settings' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload_avatar
    @user = current_user

    @user.update_attributes(user_params)

    respond_to do |format|
      format.json { render json: @user.to_json }
    end
  end

  def delete_avatar
    current_user.avatar = nil
    current_user.save
    current_user.avatar.clear #Will queue the attachment to be deleted

    respond_to do |format|
      format.json { render json: current_user.to_json }
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username,
      :email, :address, :city, :state, :country,
      :postal_code, :phone_number,
      :image_url, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
def rating_for(rateable_obj, dimension=nil, options={})

    cached_average = rateable_obj.average dimension
    avg = cached_average ? cached_average.avg : 0

    star         = options[:star]         || 5
    enable_half  = options[:enable_half]  || false
    half_show    = options[:half_show]    || true
    star_path    = options[:star_path]    || ''
    star_on      = options[:star_on]      || image_path('star-on.png')
    star_off     = options[:star_off]     || image_path('star-off.png')
    star_half    = options[:star_half]    || image_path('star-half.png')
    cancel       = options[:cancel]       || false
    cancel_place = options[:cancel_place] || 'left'
    cancel_hint  = options[:cancel_hint]  || 'Cancel current rating!'
    cancel_on    = options[:cancel_on]    || image_path('cancel-on.png')
    cancel_off   = options[:cancel_off]   || image_path('cancel-off.png')
    noRatedMsg   = options[:noRatedMsg]   || 'I\'am readOnly and I haven\'t rated yet!'
    # round        = options[:round]        || { down: .26, full: .6, up: .76 }
    space        = options[:space]        || false
    single       = options[:single]       || false
    target       = options[:target]       || ''
    targetText   = options[:targetText]   || ''
    targetType   = options[:targetType]   || 'hint'
    targetFormat = options[:targetFormat] || '{score}'
    targetScore  = options[:targetScore]  || ''
    readOnly  = (current_user == @owner) ? true : false

    disable_after_rate = options[:disable_after_rate] && true
    disable_after_rate = true if disable_after_rate == nil

    if disable_after_rate
      readonly = !(current_user && rateable_obj.can_rate?(current_user, dimension))
    else
      readonly = !current_user || false
    end

    if options[:imdb_avg] && readonly
      content_tag :div, '', :style => "background-image:url('#{image_path('/mid-star.png')}');width:61px;height:57px;margin-top:10px;" do
          content_tag :p, avg, :style => "position:relative;font-size:.8rem;text-align:center;line-height:60px;"
      end
    else
      content_tag :div, '', "data-dimension" => dimension, :class => "star", "data-rating" => avg,
                  "data-id" => rateable_obj.id, "data-classname" => rateable_obj.class.name,
                  "data-disable-after-rate" => disable_after_rate,
                  "data-readonly" => readOnly,
                  "data-enable-half" => enable_half,
                  "data-half-show" => half_show,
                  "data-star-count" => star,
                  "data-star-path" => star_path,
                  "data-star-on" => star_on,
                  "data-star-off" => star_off,
                  "data-star-half" => star_half,
                  "data-cancel" => cancel,
                  "data-cancel-place" => cancel_place,
                  "data-cancel-hint"  => cancel_hint,
                  "data-cancel-on" => cancel_on,
                  "data-cancel-off" => cancel_off,
                  "data-no-rated-message" => noRatedMsg,
                  # "data-round" => round,
                  "data-space" => space,
                  "data-single" => single,
                  "data-target" => target,
                  "data-target-text" => targetText,
                  "data-target-type" => targetType,
                  "data-target-format" => targetFormat,
                  "data-target-score" => targetScore
    end
  end

end

app/views/users/_invitations.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : <%= ENV['lenyt_facebook_key'] %>,
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<center>
  <h4><%= t "devise.invitations.new.header" %></h4>
  <br>
  <ul class="facebook">
    <li href="#" class='fb_logo'>
      <i class="fa fa-facebook"></i>
    </li>
    <li class='fb_share'>
      Share
    </li>
    <li class='fb_like'>
      Like
    </li>
  </ul>
</center>

<hr class='black'>
<h4>Invite Friends via Email</h4>
<h5>Enter their email addresses below separated by comma:</h5>
<br><br>
<%= form_for resource, as: resource_name, url: invitation_path(resource_name), html: {method: :post, id: 'vue-email', 'v-on' => 'submit: sendMails'} do |f| %>
  <%= devise_error_messages! %>

  <ul>
    <li class='email_entry' v-repeat="mails">
      <span class='email_value'>
        {{value}}
        <span v-on="click: removeMail($index)" v-class="hide: status !== 0" style="cursor:pointer"><i class="fa fa-times"></i></span>
      </span>
      <span v-class="hide: status !== -1">{{message === 'has already been taken' ? 'This user is a Lenyt member' : message}}</span>
      <span class='success' v-class="hide: status !== 1">Email successfully sent</span>
    </li>
  </ul>

<% resource.class.invite_key_fields.each do |field| -%>
  <div class="form-group">
    <%= f.text_field field, class: 'form-control noresize', placeholder: 'email address', 'v-model' =>'mail', 'v-on' => 'keyup: switchOnComma' %>
  </div>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button"), class: 'list-it col-xs-12 col-sm-12 col-md-12 col-lg-12 btn', id: 'new-listing' %></p>
<% end %>
<div class="clearfix"></div>

<script type="text/javascript">
  $('li.fb_share').click(function(event) {
    FB.ui({
      method: 'share_open_graph',
      action_type: 'og.likes',
      action_properties: JSON.stringify({
        object:'http://lenyt-dev.herokuapp.com/',
      })
    }, function(response){
      // Debug response (optional)
      console.log(response);
    });
  });
</script>

app/views/users/_payment.html.erb
<div class="tab-pane" id="payment">
  <div class="user-changes col-lg-12">
    <center>
      <div class="secure_payments">Secure Payments</div>
      <%= image_tag('powered_by_stripe.png') %>
    </center>
  </div>
  <div class="user-changes col-lg-12">
    <div class="send-money">Sending Money</div>
    <div class="col-xs-12 col-sm-4">
      Credit Card Info:
      <%= image_tag('card-icons.png') %>
    </div>
    <div class="col-xs-12 col-sm-8">
      <input type="text" class="col-xs-12 col-sm-6 width-fix" placeholder="First Name"/>
      <input type="text" class="col-xs-12 col-sm-6" placeholder="Last Name"/>
      <input type="text" class="col-xs-12 col-sm-12" placeholder="Credit Card Number"/>

      <div class="col-xs-6 col-sm-4">Expiration:</div>
      <input type="text" class="col-xs-4 col-sm-2" placeholder="Day"/>
      <input type="text" class="col-xs-4 col-sm-3" placeholder="Month"/>
      <input type="text" class="col-xs-4 col-sm-3 no-margin width-f" placeholder="Year"/>
      <input type="text" class="col-xs-4 col-sm-3 no-margin right" placeholder="CVV"/>

      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
  <div class="user-changes col-lg-12 no-border">
    <div class="send-money">Recieving Money</div>
    <div class="col-xs-12 col-sm-4">
      <span class="bank">Bank Account Info:</span>

      <div class="clear"></div>
      <input type="text" class="col-xs-12 col-sm-12" placeholder="Transit No."/>
    </div>
    <div class="col-xs-12 col-sm-8">
      <input type="text" class="col-xs-12 col-sm-6 width-fix" placeholder="First Name"/>
      <input type="text" class="col-xs-12 col-sm-6" placeholder="Last Name"/>
    </div>
    <div class="col-xs-12 col-sm-8">
      <input type="text" class="col-xs-12 col-sm-6 width-fix" placeholder="Inst. No."/>
      <input type="text" class="col-xs-12 col-sm-6" placeholder="Account No."/>
    </div>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
  <!-- <div class="line-orr">OR</div> -->
<!--   <div class="connect">
    <span>Connect your Paypal account:</span>
    <a href="#"><%#= image_tag('connect-with-paypal.png') %></a>
  </div> -->
  <div class="user-changes col-lg-12 no-border no-padding-b">
    <a href="#" class="list-it col-xs-12 col-sm-12 top-space">Save</a>
  </div>
  <div class="clear"></div>
</div>

app/views/users/_upload_avatar.haml
#uploadAvatar.modal.fade{aria: {hidden: true, labelledby: 'myModalLabel'}, role: 'dialog', tabindex: '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', aria: {label: 'Close'}, data: {dismiss: 'modal'}}= raw("<span aria-hidden='true'>&times;</span>")
        %h4.modal-title#myModalLabel= "Upload Avatar"
      .modal-body
        .form-sign
          %form
          = form_for(current_user, as: :user,  url: upload_avatar_users_path, html: { multipart: true, class: "dropzone", id: 'new_form'}) do |f|
            .fallback
              = f.file_field "avatar"

      .modal-footer
        %button.btn.btn-default{type: 'button', data: {dismiss: 'modal'}}= 'Close'

app/views/users/profile.haml
.profile-content
  %section
    // User Section
    .col-sm-12
      .shadow-box
        .user-profile
          = user_avatar(current_user, '100x100')
          %span.user-name= current_user.username
          .stars
            - 1.upto(5) do
              %span.star-active.star
            %span= ""

        .profile-actions
          .action-item.col-xs-12.col-sm-3= link_to "Account Settings", settings_users_path, class: 'settings'
          .action-item.box-center.col-xs-12.col-sm-4= raw('Total Revenue <span>$0</span>')
          .action-item.col-xs-12.col-sm-3= link_to raw("Messages<span class='redc hidden'></span>"), messages_path, class: 'messages'
          .clear
    // End User Section
    // Listing section
    .col-sm-12.listing= 'Your Listings:'
    .col-sm-12.listing-prod
      = render partial: 'listings/products'
      .clear

  %section.create-listing
    = link_to "Create New Listing", new_listing_path, class: 'shadow-box'

app/views/users/settings.haml
.account-content
  %section.content
    .col-sm-12
      .col-xs-4
        // Nav tabs
        %ul.nav.nav-tabs.tabs-left
          %li= link_to raw("<span>Profile Settings</span>"), '#settings', {data: {toggle: 'tab'}}
          %li= link_to raw("<span>Payment Settings</span>"), '#payment', {data: {toggle: 'tab'}}
          %li= link_to raw("<span>Notifications</span>"), '#notifications', {data: {toggle: 'tab'}}
          %li.active= link_to raw("<span>Invite Friends</span>"), '#invitations', {data: {toggle: 'tab'}}
      .col-xs-8
        // Tab panes
        .tab-content
          #settings.tab-pane
            = form_for current_user, url: user_path(current_user), html: { method: :put, id: 'user-form' } do |f|
              = render 'shared/errors', resource: current_user
              .user-changes.col-lg-12
                .img-content.col-sm-4
                  %a.account-link
                    #avatar
                      = user_avatar(current_user)
                    %span= link_to "Change Picture", '#', data: {toggle: 'modal', target: '#uploadAvatar'}
                    = render 'users/upload_avatar'
                .account-fields.col-sm-8
                  = f.text_field :first_name, class: 'left col-xs-12 col-sm-6 width-fix', placeholder: 'First Name'
                  = f.text_field :last_name, class: 'left col-xs-12 col-sm-6', placeholder: 'First Name'
                  = f.text_field :username, class: 'left col-xs-12  top-space', placeholder: 'User Name'
                  = f.text_field :password, class: 'left col-xs-12', placeholder: 'Password'
                  = f.text_field :password_confirmation, class: 'left col-xs-12', placeholder: 'Password Confirmation'
                  .clear
                  = link_to "Change password", '#', class: 'right account-link'
                .clear
              .user-changes.col-lg-12
                = f.text_field :address, class: 'col-xs-12 col-sm-12 top-space', placeholder: 'Address'
                = f.text_field :city, class: 'col-xs-12 col-sm-6 width-fix', placeholder: 'City'
                = f.text_field :state, class: 'col-xs-12 col-sm-6', placeholder: 'State'

                = f.text_field :postal_code, class: 'col-xs-12 col-sm-6 width-fix', placeholder: 'Postal Code'
                = f.text_field :country, class: 'col-xs-12 col-sm-6', placeholder: 'Country'
                .clear
              .user-changes.col-lg-12.no-border
                = f.text_field :phone_number, class: 'col-xs-12 col-sm-6 top-space', placeholder: 'Phone Number'
                .clear
                = f.text_field :email, class: 'col-xs-12 col-sm-6', placeholder: 'Email Address'
                .clear
              .user-changes.col-lg-12.no-border.no-padding-b
                = link_to "Save", 'javascript:{}', class: 'list-it col-xs-12 col-sm-12 top-space', onclick: "document.getElementById('user-form').submit(); return false;"

              .clear
          = render "payment"


          #notifications.tab-pane
            %input#user_updates.css-checkbox.lrg{:checked => "checked", :type => "checkbox"}/
            %label.css-label.css-checkbox.lrg.klaus{:for => "user_updates", :name => "updates"}
              Newsletter
              %br
              %span.settings Receive periodic email updates from Lenyt about discounts and other goodies
            %hr
            %input#user_notifications.css-checkbox.lrg{:checked => "checked", :type => "checkbox"}/
            %label.css-label.css-checkbox.lrg.klaus{:for => "user_notifications", :name => "nottifications"}
              Messages
              %br
              %span.settings Receive email notifications when you receive a new message or request
          #invitations.tab-pane.active
            = render 'invitations'