config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    invitations: 'users/invitations'
  } do
    # match 'settings', to: 'users/registrations#settings'
  end
  match 'auth/failure', to: redirect('/'), via: [:get]
  match 'search', to: 'listings#search', as: 'search', via: [:get]

  match 'profile', to: 'users#profile', as: 'my_profile', via: [:get]

  resources :messages, only: [:index, :show, :create]
  resources :conversations, only: [:index, :show]
  resources :users do
    collection do
      get :settings
      put :upload_avatar
      delete :delete_avatar
    end
  end
  resources :pictures
  resources :listings

  namespace :api, defaults: { format: :json } do
    get '/users/current'
    post '/rate' => 'rater#create', :as => 'rate'
    resources :users do
      collection do
        put 'newsletter_notifcations'
        put 'messages_notifcations'
      end
      member do
        get 'products'
      end
    end
    resources :products, only: [:index, :show]
    resources :requests
    resources :cities, only: :index
    resources :assets do
      member do
        delete 'delete_new_asset'
      end
    end
    resources :tags, only: :index
    resources :messages, only: :create
    resources :conversations, only: [:index, :show]
  end

  authenticated do
    root :to => 'listings#search', as: :authenticated
  end

  root to: 'home_page#index'
end

app/views/shared/_agree_modal.haml
#myModal2.modal.fade{aria: {hidden: true, labelledby: 'myModalLabel'}, role: 'dialog', tabindex: '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', aria: {label: 'Close'}, data: {dismiss: 'modal'}}= raw("<span aria-hidden='true'>&times;</span>")
      .modal-body.mCustomScrollbar
        %h3= "User Agreement"
        %p
          ==
          Welcome to the website of Lenyt (a Lenyt Camera, Inc. company project) (“Company”, “Lenyt”, “we”, or “us”). The following terms and conditions,
          together with any documents they expressly incorporate by reference, (collectively, these “Terms of Use”), govern your access to and use of Lenyt.com,
          including any content, functionality and services offered on or through Lenyt.com (the ”Website”), whether as a guest or a registered user.
          Please read the Terms of Use carefully before you start to use the Website.
          ==
        %p
          ==
          By using the Website or by clicking to accept or agree to the Terms of Use when this option is made available to you, you accept and agree to be bound and abide by these
          Terms of Use and our Privacy Policy, incorporated herein by reference. If you do not want to agree to these Terms of Use or the Privacy Policy, you must not access or use the Website.
          This Website is offered and available to users who are 13 years of age or older, and reside in the United States or any of its territories or possessions.
          By using this Website, you represent and warrant that you are of legal age to form a binding contract with the Company and meet all of the foregoing eligibility requirements.
          If you do not meet all of these requirements, you must not access or use the Website.
          ==
      .iagree= link_to "I Agree", '#'

app/views/shared/_error_messages.html.haml
.row#error_messages
  .col-md-12.col-md-12
    - if object.errors.any?
      .alert.alert-danger.alert-block
        %i.fa.fa-times.pull-right.close_alert{"data-dismiss" => "alert"}
        %br/
        %ul{:style => "padding: 0;"}
          - object.errors.full_messages.each_with_index do |msg, index|
            %li
              = msg

app/views/shared/_errors.haml
.row
  .col-md-12
    - if resource.errors.any?
      .alert.alert-danger.alert-block
        /= button_to 'x', class: 'close', data: {dismiss: 'alert'}
        %ul
          - resource.errors.full_messages.each do |msg|
            %li= msg

app/views/shared/_header.haml
%section.top-side
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle{data: {toggle: 'collapse', target: '#myNavbar'}}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to image_tag(logo_img, title: 'Lenyt - Rent camera gear locally'), root_path, class: 'logo navbar-brand'

      #myNavbar.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li= link_to "List Your Equipment", new_listing_path, class: 'list-icon'
          - if user_signed_in?
            %li
              %a{data: {toggle: 'dropdown'}}
                = current_user.full_name
                %span.user-block
                  = user_avatar(current_user)
                  %span.counti.redc.hidden= '3'
              %ul.dropdown-menu{role: 'menu', aria: {labelledby: 'dLabel'}}
                %li= link_to "Your Listings", my_profile_path
                %li= link_to raw("Messages <span class='redc hidden'>3</span>"), messages_path
                %li= link_to "Account Settings", settings_users_path
                %li= link_to "Invite Friends", settings_users_path
                %li= link_to "Log Out", destroy_user_session_path, {method: :delete}
          - else
            - if devise_mapping.registerable? && controller_name != 'registrations'
              %li= link_to "Sign Up", '#', data: {toggle: 'modal', target: '#signUpModal'}
            // %li= link_to "I agree", '#', data: {toggle: 'modal', target: '#myModal2'}
            - if controller_name != 'sessions'
              %li= link_to "Log In", '#', data: {toggle: 'modal', target: '#myModal1'}

app/views/shared/_login_form.haml
.form-sign
  .social-btns
    = link_to "Log In with Facebook", user_omniauth_authorize_path(:facebook), class: 'face'
    = link_to "Log In with Google", user_omniauth_authorize_path(:google_oauth2), class: 'google'
  .or= 'or'
  .log-inp
    = form_for(:user, url: session_path(:user), remote: true, format: :js, html: {id: 'new_user'}) do |f|
      #form_flashes
        = render 'shared/errors', resource: resource
      = f.text_field :email, autofocus: true, placeholder: 'Email Address'
      = f.password_field :password, placeholder: 'Password'
      = f.check_box :remember_me
      = f.label :remember_me
      = f.submit "Log in"
      %p.already
        = link_to "Forgot your password?", new_password_path(:user)

app/views/shared/_login_modal.haml
//Modal login
#myModal1.modal.fade{aria: {hidden: true, labelledby: 'myModalLabel'}, role: 'dialog', tabindex: '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', aria: {label: 'Close'}, data: {dismiss: 'modal'}}= raw("<span aria-hidden='true'>&times;</span>")
      .modal-body
        = render 'shared/login_form', resource: resource

app/views/shared/_sign_up_form.haml
.form-sign
  .social-btns
    = link_to "Sign Up with Facebook", user_omniauth_authorize_path(:facebook), class: 'face'
    = link_to "Sign Up with Google", user_omniauth_authorize_path(:google_oauth2), class: 'google'
  .or= 'or'
  .log-inp
    = form_for :user, url: users_path, remote: true, format: :js, html: {method: :post, id: 'user_signup_modal'} do |f|
      #form_flashes
        = render 'shared/errors', resource: resource
      = f.text_field :username, placeholder: 'Username'
      = f.text_field :email, placeholder: 'E-mail'
      = f.password_field :password, placeholder: 'Password'
      = f.password_field :password_confirmation, placeholder: 'Confirm Password'
      = f.submit "Sign Up"
%span.sign= raw("By signing up, I agree to Lenyt’s<br /> User Agreement and Terms of Services.")
%p.already
  = "Already a member? "
  = link_to 'Log In', new_session_path(:user)

app/views/shared/_sign_up_modal.haml
#signUpModal.modal.fade{aria: {hidden: true, labelledby: 'myModalLabel'}, role: 'dialog', tabindex: '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', aria: {label: 'Close'}, data: {dismiss: 'modal'}}= raw("<span aria-hidden='true'>&times;</span>")
      .modal-body
        = render 'shared/sign_up_form', resource: resource